"""
Базовий контракт для сцен (Menu/Game/Pause): методи enter/exit, handle_events, update, render, запит переходів між сценами.
"""
import pygame

class Scene:
    def __init__(self, app: "App"):
        self.app = app

    def enter(self, **kwargs): ...
    def exit(self): ...
    def handle_events(self, events): ...
    def update(self): ...
    def render(self, screen: pygame.Surface): ...
